### ISSUE TITLE
How to create PoolNormal.bam?

### ISSUE THREAD

**Issue by 1512474508** [rptashkin/facets2n#20]
Which tools can create PoolNormal.bam, samtools merge?

**Comment by rptashkin** [comment]
I have observed the best results with DNA that has been mixed from several samples (n=10) and sequenced as a single library. You could try creating a pooled BAM _in silico_ using samtools (perhaps downsample BAMs and then merge?), but I have not tested this approach. Hope that helps!

**Comment by 1512474508** [comment]
Thanks!

If I have 6 samples，I would like to get sample1_tumor.bam' snp-pileup results and run facets2n. The code as below:
inst/extcode/snp-pileup-wrapper.R
-O pooledSample1
-vcf sample1.vcf
-n sample2_normal.bam
-t sample1_tumor.bam
-un "sample3_normal.bam sample4_normal.bam sample5_normal.bam sample6_normal.bam" (not using poolNormal bam, it's right?)

     readu <- readSnpMatrix(
                    filename = "./pooledSample1.snp-pileup.gz",
                    MandUnormal = TRUE,
                    useMatchedX = FALSE)

     It's right?
