### ISSUE TITLE
how to create poolNormal bam? smatools merge?

### ISSUE THREAD

**Issue by 1512474508** [rptashkin/facets2n#22]
unmatched-normal-BAMS "<some/path>/PoolNormal.bam"

**Comment by rptashkin** [comment]
please refer to https://github.com/rptashkin/facets2n/issues/20. do you have any other questions or issue with this parameter?

**Comment by 1512474508** [comment]
Thanks!
If I have 6 samples，I would like to get sample1_tumor.bam' snp-pileup results and run facets2n. The code as below:
         inst/extcode/snp-pileup-wrapper.R 
               -O pooledSample1
               -vcf  sample1.vcf
               -n  sample2_normal.bam
               -t sample1_tumor.bam
              -un "sample3_normal.bam sample4_normal.bam  sample5_normal.bam         sample6_normal.bam"   (not using poolNormal bam, it's right?)

         readu <- readSnpMatrix(
                        filename = "./pooledSample1.snp-pileup.gz",
                        MandUnormal = TRUE,
                        useMatchedX = FALSE)

         It's right?

**Comment by 1512474508** [comment]
or run the code:
snp-pileup -g -p -A -d 20000 -r 10,0,10,10,10,10
-q 0 -Q 0 -v sample1.vcf    pooledsample1.snp-pileup.gz
sample2_normal.bam  sample1_tumor.bam <path_to_assay_specific_unmatched_diploid_normals>/*bam


But the result is not good. I'm confused how to use the unmatched  samples.

**Comment by rptashkin** [comment]
I think you have a few issues with the way you are using this tool:

1)The VCF used. The VCF should not be variant calls for a given tumor sample, but rather, a VCF of genome wide SNPs. You can download one for human genome here: ftp://ftp.ncbi.nlm.nih.gov/snp/organisms/human_9606/VCF/00-common_all.vcf.gz

2) FACETS requires a matched normal for each tumor that you are trying to analyze. Unmatched normals will help with log ratio normalization, but are optional. 

Please refer to the snp-pileup example in the README: `inst/extcode/snp-pileup-wrapper.R \
  --snp-pileup-path <optional, path to snp-pileup executable, defaults to snp-pileup in your PATH> \
  --vcf-file <path to SNP VCF> \
  --normal-bam normal.bam \
  --tumor-bam tumor.bam \
  --output-prefix <prefix for output file, preferrably tumorSample__normalSample>
  --unmatched-normal-BAMS <if using unmatched BAMs for logR normalization, e.g. "<some/path/>*-N.bam" >`

**Comment by rptashkin** [comment]
closing if no other questions
