### ISSUE TITLE
Unmatched normals in reference normals pileup vs tumor pool normal pileup

### ISSUE THREAD

**Issue by julialouw17** [rptashkin/facets2n#32]
For the --unmatched-normal-BAMS parameter, how do the inputs differ for the reference normals pileup compared to the tumor pool normal pileup? I am using roughly 45 BAMs in my reference pool for the reference pileup. However, when creating the pileup for the tumor sample, I am including the tumor BAM, matched normal BAM, and then ~5 unmatched normal BAMs that are a subset of the original larger BAM pool. I have found that when trying to read in the pileups into R using the readSnpMatrix function, I can include up to 8 unmatched normals in the tumor pileup before receiving this error: 

<img width="613" alt="image" src="https://github.com/user-attachments/assets/d93c9da1-2b1b-4ee5-a653-fd3086a8e6cc">

What exactly is the difference in function between the unmatched normals in the reference pileup vs tumor pileup? Should the tumor pileup contain a subset of the original reference pool, and how can I determine what quantity and which BAMs to include?

**Comment by rptashkin** [comment]
Hi @julialouw17 are you referencing [this step](https://github.com/rptashkin/facets2n?tab=readme-ov-file#2-snp-pileup-command-to-generate-a-counts-file-for-input-data) of the vignette in README?


 ` --normal-bam Normal.bam ` <<- this should be a single BAM from matched normal sample
 ` --tumor-bam Tumor.bam`  <<-  this should be a single BAM from the tumor sample
 ` --unmatched-normal-BAMS `  <<- this can be any number of BAMs, but should be unique samples not included in the reference pileup. In testing, this has generally been a single BAM coming from a batch control, which is a pooled normal sample that is a mixture of DNA from 10 individuals.

**Comment by julialouw17** [comment]
Yes, I was referring to step 2 of the documentation. But thank you, that answers my question about the difference between the unmatched normal BAMs in the reference and tumor pileups
